### ISSUE TITLE
Fix eclipse GWT build issues

### ISSUE THREAD

**Issue by brandonwillard** [dssg/cta-sim#5]
The maven archetype that built our skeleton project doesn't compile.  There's a maven problem with the gwt:i18n lifecycle, among other things.

**Comment by DJSekora** [comment]
Eclipse is now throwing out a series of errors:

GreetingServiceAsync cannot be resolved to a type
Messages cannot be resolved to a type
The method create(Class<?>) from the type GWT refers to the missing type GreetingServiceAsync
The method create(Class<?>) from the type GWT refers to the missing type Messages
Missing asynchronous interface GreetingServiceAsync

It appears to be unable to locate Messages.java and GreetingServiceAsync.java, which are created when the Maven project is imported into Eclipse and located in cta-webapp/target/generated-sources/gwt/dssg/client. 

Copying these files directly into the cat-webapp/src/main/java/dssg/client directory resolves all the errors, but I don't think this is a real solution.

EDIT: Resolved by modifying pom.xml to add generated-sources to the build path manually

**Comment by brandonwillard** [comment]
Is this still a problem?  If not, let's close it.

**Comment by DJSekora** [comment]
Fixed as far as I can tell.
