### ISSUE TITLE
Get OTP dev build running

### ISSUE THREAD

**Issue by brandonwillard** [dssg/cta-sim#6]
We need to get working OTP development setups working, i.e. Eclipse, git clone of OTP, running webapp with custom graph.

**Comment by DJSekora** [comment]
OTP webapp + analyst client are fully operational. Now working on batch analyst for multiple GTFS comparison.

**Comment by jpvelez** [comment]
Awesome! Please throw up a link to a password protected web demo when you
get the chance.

**Comment by DJSekora** [comment]
Do you want me to host it permanently somewhere external, or just off my computer for demonstrations?

**Comment by hunterowens** [comment]
I can set up a instance to act as the webapp host for the team.

Let me know.

**Comment by DJSekora** [comment]
That would be great. Just let me know how to publish to it when you're
finished!

**Comment by hunterowens** [comment]
How big of an instance do you need?
